services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - '3306:3306'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge